### ISSUE TITLE
Erro: Non-standard crypto library

### ISSUE THREAD

**Issue by Ali762** [WiredSolutions/react-azure-maps#77]
Using this package in Next.js gives an Error.

```import React from "react";
import {
  AzureMap,
  AzureMapsProvider,
} from "react-azure-maps";
import { AuthenticationType } from "azure-maps-control";

const option = {
  authOptions: {
    authType: AuthenticationType.subscriptionKey,
    subscriptionKey: // "mysubscriptionkeyhere",
  },
};

const DefaultMap = () => (
  <AzureMapsProvider>
    <div style={{ height: "300px" }}>
      <AzureMap options={option} />
    </div>
  </AzureMapsProvider>
);

export default DefaultMap;
```

Error: Non-standard crypto library
    at <myprojectfolder>/node_modules/react-azure-maps/dist/react-azure-maps.umd.js:137:819431

**Comment by psrednicki** [comment]
I think there problem with azure-maps-control, but I need to dive in this problem.
I found this issue https://feedback.azure.com/forums/909172-azure-maps/suggestions/41611411-nextjs-cannot-use-azure-map-control-as-package that is not resolved yet.

**Comment by str4yl1ght** [comment]
I've seen neither movement on this issue here ( [https://feedback.azure.com/forums/909172-azure-maps/suggestions/41611411-nextjs-cannot-use-azure-map-control-as-package] )  nor any workaround elsewhere. Info on using with Next.js appears sparse. Any updates?

**Comment by Mrashes** [comment]
Also would like to see anything in regards to this.  Not using Next.js but am seeing the below behavior using SitecoreJSS:

1. Testing package in storybook (playground for react components) and it works fine
2. Use Sitecore JSS to deploy & build but it throws - Non-standard crypto library
         --- Worth noting is we have our design system and sitecore repos separated 

Error: Non-standard crypto library
   at eval (webpack:///../main/node_modules/react-azure-maps/dist/react-azure-maps.es5.js?:157:819427)
   at i (webpack:///../main/node_modules/react-azure-maps/dist/react-azure-maps.es5.js?:157:819607)
   at l (webpack:///../main/node_modules/react-azure-maps/dist/react-azure-maps.es5.js?:157:819673)
   at eval (webpack:///../main/node_modules/react-azure-maps/dist/react-azure-maps.es5.js?:157:908545)
   at eval (webpack:///../main/node_modules/react-azure-maps/dist/react-azure-maps.es5.js?:157:16)
   at eval (webpack:///../main/node_modules/react-azure-maps/dist/react-azure-maps.es5.js?:157:28)
   at createCommonjsModule (webpack:///../main/node_modules/react-azure-maps/dist/react-azure-maps.es5.js?:99:35)
   at eval (webpack:///../main/node_modules/react-azure-maps/dist/react-azure-maps.es5.js?:102:17)
   at Module.../main/node_modules/react-azure-maps/dist/react-azure-maps.es5.js (D:\home\site\wwwroot\dist\sitecoreapp\server.bundle.js:18995:1)
   at __webpack_require__ (D:\home\site\wwwroot\dist\sitecoreapp\server.bundle.js:20:30)

**Comment by luca-favorido-beantech** [comment]
Same problem also using JEST. This problem is blocking all the test suite.
I'm evaluating a migration to other map solutions (also because of bundle size).
Any update could be useful, thanks!

**Comment by ptallett** [comment]
@luca-favorido-beantech This worked for me, but I have a ton of other Jest issues

https://stackoverflow.com/questions/52612122/how-to-use-jest-to-test-functions-using-crypto-or-window-mscrypto

**Comment by rbrundritt** [comment]
Azure Maps uses a standard auth library that is used by all other azure services. Under the hood it uses [window.crypto](https://caniuse.com/?search=crypto) which is a standard browser feature. It sounds like this may be a false positive in react. Here is a related post that may help provide a workaround. https://stackoverflow.com/questions/52612122/how-to-use-jest-to-test-functions-using-crypto-or-window-mscrypto

**Comment by psrednicki** [comment]
I have fix that error for NEXT.JS and update example with that in our docs: https://react-azure-maps.now.sh/live-example-map
The main problem is that you can't use map as a server side renderer - it need client side browser to work. Next is hybrid so you can add component without ssr.
